name: brightapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0 # Add the flutter_launcher_icons dependency

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.png

# Configuration for flutter_launcher_icons
flutter_icons:
  android: true    # Enable custom icons for Android
  ios: true        # Enable custom icons for iOS (if applicable)
  image_path: "assets/images/app_icon.png"  # Path to your app icon image
